/**
 * Central content/config layer for the Park City, UT STR buy-box
 * presentation webpage.
 *
 * Same template as the Charlotte, NC site (ifrahamstr.github.io/
 * CharlotteMarketAnalysis) -- same architecture (data.js -> render.js/
 * charts.js -> main.js), same CSS/component vocabulary. This file holds the
 * PROSE and config only. Every computed number lives in js/region_data.js,
 * which is AUTO-GENERATED by scripts/generate_webpage_data.py from
 * ../notebooks/parkcity_overview.ipynb -- do not hand-copy numbers here;
 * prose below that quotes a number was written against that notebook's
 * output (2026-07-29 data snapshot).
 *
 * SOURCE OF TRUTH: `Park City - UT.xlsx` -> `Cleaned_Data` sheet (145
 * listings after QC). Unlike Charlotte (where regions came from a
 * teammate's hand classification), regions here are data-derived: Ward
 * agglomerative clustering on listing coordinates, k=7, each cluster named
 * by its geography. See the notebook's "How the clusters were found".
 *
 * STATUS: Section 6 (Buy-Box Deep Dive) is intentionally blank -- the three
 * buy boxes are named and scoped from the cluster research (real N, real
 * Top 10% hit rates) but have no deep dive yet.
 */

function photo(relPath, alt, caption) {
  return { file: "assets/" + relPath, alt: alt, caption: caption };
}

const MARKET_NAME = "Park City, UT";

// ---------------------------------------------------------------------------
// Section 2 — Market context
// ---------------------------------------------------------------------------
const MARKET_OVERVIEW = {
  heading: "What Park City is",
  heroImage: photo(
    "overview/parkcity-main-street.jpg",
    "Historic Main Street in Park City, Utah, with colorful wood-frame storefronts climbing the hill under a partly cloudy sky",
    "Historic Main Street, Park City. Photo: Saalebaer, Wikimedia Commons (CC0)."
  ),
  chips: [
    { label: "Largest Ski Resort in the U.S. — 7,300 acres" },
    { label: "2002 Olympic Host · 2034 Winter Games Return" },
    { label: "Deer Valley Doubled to 4,300+ Acres" },
    { label: "~35 mi / 40–45 min from SLC Airport" },
  ],
  attractions: [
    "<strong>Park City Mountain</strong> (Vail) — 41 lifts, linked to Canyons Village; new Canyons Village Skyway gondola for 2026/27.",
    "<strong>Deer Valley</strong> — Expanded Excellence added 10 lifts and a new <strong>East Village</strong> base on the Jordanelle side (4,500 acres for 2026/27; lodges due 2027/28).",
    "<strong>Historic Main Street</strong> — dining, galleries, Egyptian Theatre, and the Town Lift straight onto the mountain.",
    "<strong>Utah Olympic Park &amp; Soldier Hollow</strong> — 2002 venues, both in the 2034 Winter Games plan.",
    "<strong>Heber Valley summer</strong> — Jordanelle &amp; Deer Creek reservoirs, Homestead Crater (Midway), Heber Valley Railroad.",
  ],
  visitorStats: {
    headline: "3.7M overnight visitors · $1.6B visitor spending (Park City, 2023)",
    breakdown: [
      { value: "$2.2B", label: "Total Economic Impact (Park City)" },
      { value: "$1.65B", label: "Summit County Visitor Spend — #2 in Utah" },
      { value: "$477", label: "Wasatch County Avg Hotel Rate (2025) — Highest in UT" },
      { value: "52%", label: "Summit Co. Share of Utah's Snow-Sports Economy" },
    ],
  },
  // Demand watch-outs -- both are material to how the 2026-07-29 revenue
  // snapshot should be read, so they sit right in the market section.
  watchOuts: [
    "❄️ <strong>2025/26 was Utah's worst snow year on record</strong> — statewide skier days fell 26.5% and Summit County posted the largest room-tax decline of any Utah county. The dataset's trailing revenue includes that winter, so it likely <em>understates</em> a normal-snow year.",
    "🎬 <strong>Sundance has left Park City.</strong> The 2026 festival was the last one here; it moves to Boulder, CO from January 2027 — the late-January demand spike (strongest in Old Town) is gone going forward.",
    "☀️ <strong>Summer is carrying more weight</strong> — the low-snow winter pushed visitation into summer (May 2026 lodging up ~22% YoY), which favors the Heber Valley / Jordanelle reservoir side of the market.",
  ],
  sources: [
    { label: "Park City Mountain — mountain info", url: "https://www.parkcitymountain.com/the-mountain/about-the-mountain/mountain-info.aspx" },
    { label: "Deer Valley — Expanded Excellence updates", url: "https://www.deervalley.com/media-room/062926-ee-updates" },
    { label: "Park Record — Park City tourism economic impact", url: "https://www.parkrecord.com/2024/11/07/park-city-pulse-character-and-tourism-grow-together/" },
    { label: "Park Record — Summit County visitor spending", url: "https://www.parkrecord.com/2024/09/06/summit-county-ranks-second-in-the-state-for-visitor-spending/" },
    { label: "KPCW — Wasatch County hotel rate", url: "https://www.kpcw.org/wasatch-county/2026-03-19/wasatch-county-averages-highest-hotel-nightly-rate-in-utah" },
    { label: "TownLift — 2025/26 skier days & room tax", url: "https://townlift.com/2026/08/skier-days-fell-26-5-in-utahs-worst-snow-year-handing-summit-county-the-states-largest-room-tax-decline/" },
    { label: "Sundance Institute — 2027 Boulder dates", url: "https://www.sundance.org/blogs/2027-sundance-film-festival-to-take-place-january-21-31-in-boulder-colorado/" },
    { label: "KPCW — low-snow winter drives summer visitation", url: "https://www.kpcw.org/summit-county/2026-06-22/park-city-chamber-low-snow-winter-drives-summer-visitation-increase" },
  ],
};

// ---------------------------------------------------------------------------
// Section 3 — Location analysis. The map itself is the embedded folium map
// built in parkcity_overview.ipynb (assets/overview/parkcity_overview_map.html).
// ---------------------------------------------------------------------------
const MAP_CONFIG = {
  stateAbbr: "UT",
  marketInterpretation:
    "The map combines two filters (check both a tier and a region to isolate a slice — e.g. <em>Top 10%</em> + <em>Heber Valley</em>): <strong>revenue tier</strong> (market-wide Top 10% / Top 25% / Other 75%) and <strong>region</strong> — seven clusters found directly from listing coordinates, each named for the real place it covers. Hover a dashed outline for that region's scorecard; the layer control (top-right) adds ski bases, towns, lakes, attractions and airports. The market splits cleanly into a <strong>Park City side</strong> (four regions ringing the resorts) and a <strong>Heber side</strong> (three regions across the Jordanelle and Heber Valley):",
  regionBullets: [
    "⛷️ <strong>Old Town &amp; Deer Valley</strong> — the walk-to-lift core, and the strongest region per listing and per bedroom.",
    "🌲 <strong>Summit Park &amp; Pinebrook</strong> — forested hillside cabins off I-80; the biggest group houses and two of the market's top four earners.",
    "🏔️ <strong>Jordanelle &amp; Hideout</strong> — Deer Valley's new East Village side; the highest median revenue in the market, but no breakout Top 10% listings yet.",
    "🛖 <strong>Pine Meadow &amp; Rockport</strong> — cabin communities \"above Park City\"; small cabins here out-earn small units anywhere else.",
    "🏘️ <strong>Snyderville Basin</strong> — Canyons Village, Kimball Junction and Silver Creek; condo- and townhome-heavy, the weakest region on the Park City side.",
    "🧀 <strong>Midway</strong> — the Swiss-themed village by Homestead Crater; steady small product, no Top 10% listings.",
    "🐄 <strong>Heber Valley</strong> — the largest region and the most bimodal: basement units below market, 5BR+ group homes well above it.",
  ],
};

// How the clusters were found -- rendered as a short bullet list above the
// region scorecard.
const CLUSTER_METHOD = [
  "<strong>Data-derived, then named.</strong> No teammate region file exists for this market, so regions come straight from the 145 listings' coordinates — Ward-linkage clustering on a km-projected lat/long grid — and each cluster is then named for the real place it covers.",
  "<strong>Why seven.</strong> k = 4 to 10 were tested with KMeans and Ward side by side (the two give near-identical silhouette scores at every k). Seven is the first k where every cluster is one real, named place (silhouette 0.62). Above seven, clustering only splits off 3–5-listing pockets, which are too thin to underwrite. They are noted inside their parent region instead.",
  "<strong>Hit rates are market-wide.</strong> A region's Top 10% hit rate uses the market's P90 threshold, not one recomputed inside the region, so regions compare like-for-like. The same convention is used on Charlotte, Shenandoah and Clearwater.",
];

// Per-region narrative for the region profile cards. Numbers quoted here
// come from parkcity_overview.ipynb (region scorecard, size-controlled
// table, k=8-10 sub-pocket splits).
const REGION_PROFILES = {
  oldtown: {
    headline: "The walk-to-lift core, and the market's strongest location",
    bullets: [
      "<strong>Location, not size, is the premium here.</strong> Holding bedroom count fixed, a 3BR earns a median $80k (market 3BR: $56k) and a 4BR $142k (market: $70k), roughly double.",
      "<strong>Highest revenue per bedroom</strong> in the market ($25.9k). Titles sell proximity: <em>\"Steps from Main St\"</em>, <em>\"Near Town Lift\"</em>, <em>\"Ski-in/out\"</em>.",
      "<strong>Why the median looks ordinary ($59k):</strong> 9 of 22 listings are 1–2BR condos and historic cottages (median $44k). At 3BR+, the Top 10% hit rate is 38%.",
      "<strong>Adult ski and après product:</strong> the lowest stayed-with-kids share of any region (15%).",
    ],
  },
  summitpark: {
    headline: "Forest cabins for big groups, with the widest spread",
    bullets: [
      "<strong>Holds the market's #1 earner</strong> (<em>\"Park City Pines retreat sleeps 22\"</em>, $345k) and #4 (<em>\"The Views at Matterhorn\"</em>, $205k).",
      "<strong>The biggest group product:</strong> median sleeps 10.5, the highest group-trip share of any region (39%) and the highest hot-tub rate (83%).",
      "<strong>Wide spread:</strong> the 4BR median is only $71k. The winners are the very large, view-heavy lodges, not every cabin.",
      "7–9 km from Canyons Village via I-80. Winter access is steep, and the median annual cleaning fee is the market's highest ($13.4k).",
      "⚠️ <strong>Regulatory risk:</strong> Summit Park is on Summit County's proposed nightly-rental ban list (June 2026, no final vote found).",
    ],
  },
  jordanelle: {
    headline: "The Deer Valley East side: a consistent mid-tier with no breakout listings yet",
    bullets: [
      "<strong>Highest median revenue ($70k) and occupancy (54%) of any region</strong>, and 42% of listings clear the Top 25% line.",
      "<strong>No Top 10% listings:</strong> the biggest house here is a 4BR, so the region has no 5BR+ group product.",
      "Listings sit 1–5 km from Deer Valley's Jordanelle gondola and the new <strong>East Village</strong> base. The data covers only one East Village season, and it was a record-low snow year.",
      "Includes Hideout, which has a Kamas mailing address but sits on the Jordanelle shore.",
    ],
  },
  pinemeadow: {
    headline: "Small cabins that out-earn small units anywhere else",
    bullets: [
      "<strong>1–2BR median $55k</strong>, the highest small-unit revenue in the market (market 1–2BR: $34k), at 62% occupancy.",
      "The product is the escape itself: <em>\"Dreamy Living Treehouse\"</em>, <em>\"Secluded Hideaway Above Park City\"</em>, <em>\"Bullmoose Cabin\"</em>.",
      "<strong>Big houses don't scale here:</strong> the 5BR+ median is $62k. One outlier (<em>\"Luxury Mountain Living\"</em>, 7BR, $202k) is the region's only Top 10% listing.",
      "<strong>Sub-pocket:</strong> 3 rural Coalville/Wanship listings (median $32k) trail the Pine Meadow Ranch core (14 listings, median $62k).",
      "⚠️ <strong>Regulatory risk:</strong> Pine Meadow sits in the Tollgate Canyon area, which is on Summit County's proposed ban list.",
    ],
  },
  snyderville: {
    headline: "Condo and townhome inventory, the weakest region on the Park City side",
    bullets: [
      "<strong>Median $45k, ADR $330:</strong> the lowest of the four Park City-side regions, despite being next to Canyons Village and Kimball Junction.",
      "<strong>Only 2 Top 10% listings</strong> (<em>\"2 Mi to Cabriolet Lift\"</em>, $157k; <em>\"Ski &amp; Tee Mountain Chalet\"</em>, $129k).",
      "<strong>Sub-pockets:</strong> Canyons/Kimball (9 listings, mostly 1–2BR resort condos such as Westgate and Newpark) and Silver Creek Village (14 listings, newer 4–5BR townhomes). The two medians are nearly identical ($44k and $47k).",
      "Heavy resort-condo supply here competes directly with hotels.",
    ],
  },
  midway: {
    headline: "A charming village with a capped ceiling",
    bullets: [
      "<strong>No Top 10% listings, and only 11% reach the Top 25%.</strong> 42% of listings are 1–2BR, including three rooms split from a single property.",
      "3BR cabins on the west bench perform respectably (median $57k), but nothing scales. The best result is a 6BR at $69k.",
      "Demand comes from Homestead Crater, Soldier Hollow, golf and Swiss Days, which is a summer and shoulder-season story.",
      "Lowest pet share in the market (2.5%).",
      "STRs are legal only inside the city's overlay zone, which was reduced on Sept 1, 2026.",
    ],
  },
  heber: {
    headline: "Two markets in one: basement units and big group homes",
    bullets: [
      "<strong>The largest region (28% of listings) and the most bimodal.</strong> The 25 listings at 4BR or under earn a median $28k (many are basement apartments). The 15 at 5BR+ earn a median $80k, and 5 of them (33%) reach the Top 10%.",
      "<strong>Heber holds a third of the market's Top 10%</strong>, tied with Old Town (5 listings each), and every one of them is 5–8BR sleeping 14–16.",
      "<strong>The winners sit on the edges, not in town:</strong> on the north bench near Red Ledges (<em>\"Heber Heights\"</em>, <em>\"Luxury Home… Spa, View\"</em>, $237k) and to the south by Deer Creek (<em>\"Resort Home, Sleeps 20\"</em>, $171k).",
      "<strong>Sub-pocket:</strong> 5 Timber Lakes and east-bench listings (median $29k) are small, remote and weak.",
      "Highest stayed-with-kids share (27%): this is family-reunion product.",
    ],
  },
};

// ---------------------------------------------------------------------------
// Section 4 — Traveller demographics note (numbers in region_data.js)
// ---------------------------------------------------------------------------
const DEMOGRAPHICS_NOTE =
  "These are review-derived guest-composition signals (the share of reviews mentioning stays with kids, group trips or pets), not verified traveler demographics. As in Charlotte, group trips climb steeply with size, from under 6% at 1–2BR to roughly half at 5BR+. Park City's large homes also carry a real family signal: kids appear in about a third of 5BR+ reviews. By region, Summit Park is the most group-heavy and Heber the most family-heavy. Old Town has the lowest kids share of any region, consistent with an adult ski and après crowd.";

// ---------------------------------------------------------------------------
// Section 5 — STR regulations. The market spans several jurisdictions, so
// this renders one overall card plus one card per jurisdiction.
// ---------------------------------------------------------------------------
// Research as of 2026-09-28. "Unverified" marks claims sourced only from
// news or secondary sites, or where the official page could not be loaded.
// Tier keys: friendly / moderate / restrictive (CSS color only).
const STR_REGULATIONS = {
  overview: {
    tier: "Mixed — Moderate in the Resort Cores, Restrictive and Tightening at the Edges",
    tierKey: "moderate",
    tierNote:
      "The market spans seven-plus jurisdictions, and the rules change at every line. Park City, Heber City and Hideout license STRs with firm operating rules. Unincorporated Summit County licenses them today but proposed neighborhood bans in June 2026. Midway, Kamas and Coalville restrict them through overlay zones, moratoria and caps. Diligence is address-level: zoning, HOA/CC&Rs <em>and</em> jurisdiction all have to allow nightly rental.",
    permitResidency: [
      "A license or permit is required in every jurisdiction here. No primary-residence requirement was found for whole-home rentals.",
      "Property tax: nightly rental generally forfeits Utah's primary-residence exemption. Summit County presumes non-primary after 14 rented nights a year; Wasatch County allows 2 weeks.",
    ],
    operatingLimits: [
      "<strong>Utah HB 256 (2025, effective May 7, 2025):</strong> cities and counties still can't fine someone for listing alone, but they may now use a listing as evidence together with other information, require a license, and ask a platform to take down a non-compliant listing.",
      "<strong>Lodging tax (estimated, about 13–15% all-in):</strong> Park City ~14.6%, unincorporated Summit County ~12.8%, Heber and Midway ~13–14%. HB 456 raised the state TRT to 1.07% and let Wasatch County reach 4.5%. Airbnb and Vrbo collect it. Totals are unverified against official Tax Commission rate charts.",
    ],
    investorNotes: [
      "⚠️ <strong>The biggest live risk is Summit County's proposed nightly-rental bans</strong> in Summit Park, Tollgate Canyon (Pine Meadow Ranch area), Rockport Estates, Samak and others. This is the Mountain Cabin buy box's territory. A draft ordinance was due in August 2026, and no final vote had been found as of late September.",
      "Watch for Summit County, Colorado results: its caps and waitlists do <em>not</em> apply to Summit County, Utah.",
    ],
    sources: [
      { label: "Utah HB 256 (2025)", url: "https://le.utah.gov/Session/2025/bills/enrolled/HB0256.pdf" },
      { label: "Utah HB 456 (2025)", url: "https://le.utah.gov/Session/2025/bills/enrolled/HB0456.pdf" },
      { label: "Summit County nightly rental staff report", url: "https://summitcountyutah.gov/DocumentCenter/View/20856/Staff-Report-Nightly-Rentals" },
    ],
  },
  byRegionNote:
    "Jurisdiction by region: <strong>Old Town &amp; Deer Valley</strong> → Park City · <strong>Snyderville Basin, Summit Park &amp; Pinebrook, Pine Meadow &amp; Rockport</strong> → unincorporated Summit County (the Coalville mailing addresses in Pine Meadow are <em>not</em> Coalville city) · <strong>Jordanelle &amp; Hideout</strong> → Town of Hideout, MIDA (Deer Valley East Village) and unincorporated Wasatch County · <strong>Heber Valley</strong> → Heber City, plus unincorporated Wasatch County at the edges · <strong>Midway</strong> → Midway City.",
  jurisdictions: [
    {
      jurisdiction: "Park City (Municipal)",
      covers: "Old Town & Deer Valley region · Old Town Ski-Access buy box",
      tier: "Moderate — Open in Resort Zones, Closed in Many Neighborhoods",
      tierKey: "moderate",
      tierNote: "Each unit needs its own nightly rental license, renewed yearly, with an inspection before it is advertised. The real constraint is zoning.",
      permitResidency: [
        "Per-unit nightly rental license plus a sales tax number (Muni Code 4-5-3). Fee amount unverified (the fee schedule could not be loaded).",
        "No primary-residence requirement, and no citywide cap or moratorium.",
      ],
      operatingLimits: [
        "<strong>Allowed</strong> in HR-1, R-1, Estate and most RD zones.",
        "<strong>Prohibited</strong> in the Single Family zone (except Prospector Village), in HRL McHenry Ave, and in named RD subdivisions (April Mountain, Mellow Mountain Estates, Meadows Estates 1A/1B, Fairway Meadows, Hidden Oaks at Deer Valley 2–3, Chatham Crossing, West Ridge).",
        "HRL Western (Sampson, Ridge, King Rd): conditional use permit, capped at 12 CUPs. Lockout units need a CUP.",
        "A responsible party within one hour's drive who answers within 20 minutes; year-round off-street parking; snow removal and trash rules.",
      ],
      investorNotes: [
        "Check the city's address lookup map <em>and</em> the HOA/CC&Rs for every candidate.",
        "<strong>Bonanza Park:</strong> a draft district code would prohibit new nightly rentals. Still pending as of Sept 2026.",
        "Park City has the highest STR share of housing in Utah (41%), and 2025 room tax ended down 9%.",
      ],
      sources: [
        { label: "Muni Code 4-5-3", url: "https://parkcity.municipalcodeonline.com/book/print?type=ordinances&name=4-5-3_Regulation_Of_Nightly_Rentals" },
        { label: "RD district (banned subdivisions)", url: "https://parkcity.municipalcodeonline.com/book/print?type=ordinances&name=15-2.13_Residential_Development_%28RD%29_District" },
        { label: "Address lookup map", url: "https://www.arcgis.com/apps/InformationLookup/index.html?appid=3314197a18c542b6a39ff908ddc3cc30" },
        { label: "KPCW — Bonanza Park", url: "https://www.kpcw.org/park-city/2025-05-21/park-city-council-to-discuss-bonanza-park-code-changes-including-height-and-nightly-rentals" },
      ],
    },
    {
      jurisdiction: "Unincorporated Summit County",
      covers: "Snyderville Basin · Summit Park & Pinebrook · Pine Meadow & Rockport · Mountain Cabin buy box",
      tier: "Moderate Today — Restrictive Trend, High Risk in Remote Neighborhoods",
      tierKey: "restrictive",
      tierNote: "Licensing is straightforward today, but the county is actively moving to close nightly rentals in wildfire-exposed, single-access neighborhoods.",
      permitResidency: [
        "Nightly rental license (County Code 3-1D) for both the owner and the manager, <strong>$350</strong>, with an inspection for new licenses.",
        "No primary-residence requirement. Nightly rental of ADUs and guest houses has been banned since Nov 2023.",
      ],
      operatingLimits: [
        "No numeric occupancy cap and no STR-specific zone; the license can be revoked for noise, occupancy loads, parking or nuisance.",
        "A complaint hotline launched Jan 2026. About 1,900 STRs have been identified, about 1,300 of them licensed.",
      ],
      investorNotes: [
        "⚠️ <strong>Proposed neighborhood bans (June 2026):</strong> Summit Park, Timberline, Tollgate Canyon, Stagecoach Estates, Browns Canyon, Rockport Estates, Upper Weber Canyon, Samak, parts of Woodland and Kimball Canyon Rd. No final vote found as of late Sept 2026.",
        "Pine Meadow Ranch sits in the Tollgate Canyon area. Its inclusion in the ban area is likely but unconfirmed. The HOA regulates rentals but says it can't ban them.",
        "Canyons Village and Kimball Junction resort areas aren't on the list, but many Basin subdivisions ban nightly rental in their CC&Rs.",
      ],
      sources: [
        { label: "Summit County business licensing", url: "https://www.summitcountyutah.gov/274/Business-Licensing" },
        { label: "KPCW — proposed neighborhood bans", url: "https://www.kpcw.org/summit-county/2026-06-05/summit-county-considers-nightly-rental-ban-in-some-neighborhoods" },
        { label: "Park Record — council to consider restrictions", url: "https://www.parkrecord.com/2026/06/05/summit-county-council-to-consider-restricting-short-term-rentals-in-certain-neighborhoods-this-summer/" },
      ],
    },
    {
      jurisdiction: "Heber City",
      covers: "Heber Valley region · Heber Group Home buy box",
      tier: "Moderate — Allowed With a License and Firm Operating Rules",
      tierKey: "moderate",
      tierNote: "Heber allows whole-home STRs in detached single-family homes, and its occupancy cap lines up with the buy box's sleeps-14–16 spec.",
      permitResidency: [
        "Business license plus Wasatch County Health and Fire inspections (Ch. 5.26, amended by Ord. 2025-12). Base fee unverified; about $300 all-in by one secondary estimate.",
        "Whole-home rentals: no owner occupancy required. Renting part of a home requires the owner on site.",
      ],
      operatingLimits: [
        "<strong>Detached single-family homes only</strong>, unless a development agreement says otherwise.",
        "<strong>1 guest per 200 sq ft, maximum 16</strong> on the property at any time. A listing advertising \"Sleeps 20\" would exceed this cap.",
        "Rental manager within 10 miles, 24/7. All parking on paved on-site surfaces, no street parking. Quiet hours 10 pm–7 am.",
      ],
      investorNotes: [
        "Several of Heber's Top 10% homes sit on the valley's edges. Confirm Heber City limits against <strong>unincorporated Wasatch County</strong> (restrictive by default) or Charleston at the address level.",
        "Penalties run up to $200 a day (civil). Ord. 2025-27 exists but was not reviewed.",
      ],
      sources: [
        { label: "Heber City Code 5.26", url: "https://heber.municipalcodeonline.com/book/print?type=ordinances&name=5.26_Short_Term_Rentals" },
        { label: "KPCW — Heber updates STR rules", url: "https://www.kpcw.org/heber-city/2025-06-18/your-neighbors-are-watching-you-heber-updates-short-term-rental-rules" },
      ],
    },
    {
      jurisdiction: "Wasatch County, MIDA & Hideout",
      covers: "Jordanelle & Hideout region (watch list) · Heber Valley edges",
      tier: "Restrictive by Default — Moderate Inside Approved Developments",
      tierKey: "moderate",
      tierNote: "Outside the towns, Wasatch County allows STRs only where both the zone (or a development agreement) and the CC&Rs allow them. Deer Valley East Village sits largely in a MIDA project area with its own licensing.",
      permitResidency: [
        "Unincorporated Wasatch County: a license is required ($50/yr in 2022; current fee unverified). Code 11.08 requires both CC&Rs and zoning to allow STRs (per a secondary quote).",
        "MIDA (East Village / Mayflower): MIDA STR business license, stays of 3–30 nights. Conflicting MIDA FAQ language, so verify parcel by parcel.",
        "Town of Hideout: business license, annual health and fire inspection, and a licensed manager on site within 30 minutes (Ord. 2023-O-07).",
      ],
      operatingLimits: [
        "Timber Lakes: STRs reported illegal (secondary source), consistent with that pocket's weak numbers.",
        "Hideout fees, zones and occupancy limits are unverified.",
      ],
      investorNotes: [
        "The Jordanelle watch-list segment carries MIDA and HOA uncertainty on top of its revenue ceiling. Treat it as research-only until the rules are confirmed.",
      ],
      sources: [
        { label: "Hideout Title 4.07", url: "https://hideout.municipalcodeonline.com/book/print?type=ordinances&name=4.07_Regulation_Of_Short_Term_(Nightly)_Rentals" },
        { label: "MIDA planning & zoning", url: "https://www.midaut.org/planning-zoning-and-permits" },
        { label: "KPCW — Wasatch County STR rules", url: "https://www.kpcw.org/wasatch-county/2022-03-24/wasatch-county-officials-looking-into-new-short-term-rental-rules" },
      ],
    },
    {
      jurisdiction: "Midway City",
      covers: "Midway region (excluded)",
      tier: "Restrictive — Overlay Zone Only, and Shrinking",
      tierKey: "restrictive",
      tierNote: "STRs are allowed only inside the Transient Rental Overlay District (TROD), and the city cut that zone back on Sept 1, 2026.",
      permitResidency: [
        "Owner business license <strong>and</strong> a Midway-licensed property manager with a Wasatch County office.",
        "Ord. 2025-17: exterior 24/7 contact plaque, whole-unit rentals only, dark-sky lighting, possible permanent revocation.",
      ],
      operatingLimits: [
        "<strong>The TROD was reduced on Sept 1, 2026.</strong> Removed areas include Turnberry, Midway Village, Rising Ranch, some Mountain Spa lots and east of Fox Den Rd. Existing licensed STRs are grandfathered.",
        "Only 59 of the city's 349 counted STR units (17%) were licensed.",
      ],
      investorNotes: ["Supports Midway's exclusion: a capped revenue ceiling and a shrinking legal footprint."],
      sources: [
        { label: "Park Record — Midway reduces STR zone", url: "https://www.parkrecord.com/2026/09/08/midway-reduces-short-term-rental-zone-after-complaints-from-property-owners/" },
        { label: "KPCW — Midway rule updates", url: "https://www.kpcw.org/wasatch-county/2025-12-09/midway-updates-short-term-rental-rules-for-better-oversight" },
      ],
    },
    {
      jurisdiction: "Kamas & Coalville (City Limits)",
      covers: "Outlying listings only. Pine Meadow and Hideout are separate jurisdictions despite their mailing addresses.",
      tier: "Restrictive — Moratorium (Kamas) and Hard Cap (Coalville)",
      tierKey: "restrictive",
      tierNote: "Both small cities have effectively closed or capped new STR supply.",
      permitResidency: [
        "<strong>Kamas:</strong> moratorium on new STR licenses since March 2025. Existing STRs registered by Apr 10, 2025 are grandfathered. A 1% city TRT was added.",
        "<strong>Coalville:</strong> business license with HOA consent; owner on site or manager within 10 miles.",
      ],
      operatingLimits: [
        "<strong>Coalville cap:</strong> 5% of primary households citywide, and no more than 3 STRs within a 500-ft radius. 1 guest per 200 sq ft, maximum 12; at most 4 cars.",
      ],
      investorNotes: ["Not a target for any buy box."],
      sources: [
        { label: "KPCW — Kamas moratorium", url: "https://www.kpcw.org/summit-county/2025-03-17/kamas-pauses-new-short-term-rentals-adds-tax-for-guests" },
        { label: "Coalville Development Code", url: "https://media.rainpos.com/3855/CoalvilleCityDevCode_061024_20240610112643.pdf" },
      ],
    },
  ],
  verifiedNote:
    "Researched 2026-09-28 from official codes, ordinances and bill text where they were reachable, and from Park Record, KPCW and TownLift reporting otherwise. Not verified: official combined lodging-tax rates, Park City and Hideout fee amounts, MIDA's EO 2025-09, and whether Summit County has voted on the neighborhood bans since August 2026. None of this is legal advice; every candidate property needs address-level confirmation.",
};

// ---------------------------------------------------------------------------
// BUY_BOXES — Section 1 declarations only. Region + the product that wins
// there (the size-controlled analysis shows region alone isn't enough).
// Ordered weakest to strongest by Top 10% hit rate, like Charlotte. Segment
// stats are REGION_RESEARCH.segments[*] (region_data.js). No deep dive is
// built yet: Section 6 is intentionally blank.
// ---------------------------------------------------------------------------
const BUY_BOXES = [
  {
    id: "mountain",
    segmentKey: "mountain",
    label: "Mountain Cabin Buy Box",
    name: "Summit Park, Pinebrook & Pine Meadow — 4BR+ Group Cabins",
    thesis:
      "Big forested cabins for groups off the I-80 corridor and above Rockport. This segment holds the market's #1 earner, but the spread is wide, so views and lodge-scale layouts separate the winners from the pack.",
    atAGlance: {
      bedBath: "4BR+ · 3.5 baths median",
      sleeps: "10+ (median 14)",
      heroMechanism: "Hot tub (92% of the segment) + game room (62%), views, forest seclusion",
      regulatory: "⚠️ <strong>On hold.</strong> Summit Park and Tollgate Canyon (Pine Meadow) are on Summit County's proposed nightly-rental ban list (June 2026), and no final vote has been found. Don't acquire until it is resolved.",
    },
  },
  {
    id: "heber",
    segmentKey: "heber",
    label: "Heber Group Home Buy Box",
    name: "Heber Valley — 5BR+ Group Homes, Sleeps 14+",
    thesis:
      "Heber's median is the market's lowest, yet it ties Old Town for the most Top 10% listings. Every one of them is a 5–8BR home sleeping 14–16 on the valley's edges (the north bench by Red Ledges, or south toward Deer Creek), sold to family reunions and large groups.",
    atAGlance: {
      bedBath: "5BR+ · 3.5 baths median",
      sleeps: "14+ (median 16)",
      heroMechanism: "Headcount + hot tub (86%) + game room (64%); pickleball, sauna and theater on the top earners",
      regulatory: "Moderate. Heber City licenses detached single-family STRs with a 16-guest cap, which fits the spec. Confirm the address isn't in unincorporated Wasatch County, which is restrictive by default.",
    },
  },
  {
    id: "oldtown",
    segmentKey: "oldtown",
    label: "Old Town Ski-Access Buy Box",
    name: "Old Town & Deer Valley — 3BR+ Walk-to-Lift",
    thesis:
      "The walkable Main Street, Town Lift and Deer Valley core. It has the only size-controlled location premium in the market: 3BR and 4BR homes here earn 1.4–2× their market-wide peers, at a median 0.7 km from a lift.",
    atAGlance: {
      bedBath: "3BR+ · 3.5 baths median",
      sleeps: "6+ (median 10)",
      heroMechanism: "Walk to Main Street / Town Lift / Deer Valley + hot tub (77%)",
      regulatory: "Moderate. A per-unit city license is required, and zoning is decisive: HR-1, R-1, Estate and most RD zones allow nightly rental, while SF, HRL McHenry and several RD subdivisions don't. Check HOA rules too.",
    },
  },
];

// Section 7 -- coverage. Every box is pending (no deep dive yet); the watch
// list and exclusions are part of the coverage story, straight from the
// notebook's "Why These Buy Boxes" segmentation.
const PENDING_BUY_BOXES_NOTE =
  "All three buy boxes are named and scoped from the cluster research, with real N and market-wide Top 10% hit rates. None has a deep dive yet (comp sets, revenue tiering, amenity and photo evidence); Section 6 is intentionally blank until those are built. One segment is on the watch list and two are excluded:";
const PENDING_BUY_BOXES = [
  { eyebrow: "Pending · regulatory hold", label: "Mountain Cabin Buy Box", segmentKey: "mountain", note: "Deep dive not started. On hold pending Summit County's vote on nightly-rental bans in Summit Park and Tollgate Canyon (see Section 5)." },
  { eyebrow: "Pending", label: "Heber Group Home Buy Box", segmentKey: "heber", note: "Deep dive not started." },
  { eyebrow: "Pending", label: "Old Town Ski-Access Buy Box", segmentKey: "oldtown", note: "Deep dive not started." },
  { eyebrow: "Watch list", label: "Jordanelle & Hideout 4BR+", segmentKey: "jordanelle_watch", note: "Highest median revenue in the market and 57% reach the Top 25%, but none reach the Top 10% and there is no 5BR+ inventory. Revisit after a normal-snow season with Deer Valley East Village fully open." },
  { eyebrow: "Excluded", label: "All 1–2BR", segmentKey: "small_all", note: "None of the market's 53 1–2BR listings reach the Top 10%, and only 2 reach the Top 25%. Pine Meadow's small cabins are the one bright spot, and even they top out below the P75 line." },
  { eyebrow: "Excluded", label: "Snyderville Basin & Midway", note: "Neither region has a product that reliably reaches the top band. Snyderville has the lowest median on the Park City side ($45k), and its resort condos compete with hotels. Midway has no Top 10% listings, its best listing tops out at $76k, and the city shrank its STR overlay zone on Sept 1, 2026." },
];
