/**
 * Leaflet/OpenStreetMap interactive maps. Reads webpage/data/listings.json
 * (generated by scripts/generate_webpage_map_data.py from the raw market CSV;
 * do not hand-edit).
 *
 * The Section 3 map is market-wide and filters only by market-wide revenue
 * tier. The 4BR deep-dive map is separate and derives comp identity from
 * BUY_BOXES, then joins coordinates by Property ID from listings.json.
 *
 * ZIP overlay: webpage/data/listings.json's `zipApprox` array gives one
 * centroid + radius per ZIP, computed directly from that ZIP's own listing
 * coordinates (see scripts/generate_webpage_map_data.py). These are drawn as
 * subtle dashed circles with a ZIP-code label: an approximation, NOT
 * authoritative ZCTA boundary lines. Documented integration point: drop a
 * real `webpage/data/zip-boundaries.geojson` next to listings.json and this
 * file will render it via L.geoJSON instead of approximate circles.
 */
let LEAFLET_MAP = null;
let MARKER_LAYER = null;
let ZIP_LAYER = null;
let ALL_LISTINGS = [];
let ACTIVE_TIERS = new Set(Object.keys(MAP_CONFIG.tierLabels));
let LISTINGS_PAYLOAD_PROMISE = null;

let FOUR_BR_COMP_MAP = null;
let FOUR_BR_COMP_MARKER_LAYER = null;
let FOUR_BR_ACTIVE_CATEGORIES = new Set(Object.keys(MAP_CONFIG.fourBrCompCategories));

function escapeHtml(s) {
  const div = document.createElement("div");
  div.textContent = s == null ? "" : String(s);
  return div.innerHTML;
}

function loadListingsPayload() {
  if (!LISTINGS_PAYLOAD_PROMISE) {
    LISTINGS_PAYLOAD_PROMISE = fetch(MAP_CONFIG.dataUrl).then((r) => r.json());
  }
  return LISTINGS_PAYLOAD_PROMISE;
}

function markerTooltipHtml(listing) {
  return (
    "<strong>" + escapeHtml(listing.title) + "</strong><br>" +
    escapeHtml(listing.city) + ", " + MAP_CONFIG.stateAbbr + " " + escapeHtml(listing.zip) + " · " + listing.bedrooms + "BR<br>" +
    "Revenue: " + fmtCurrency(listing.revenue) + " · ADR: " + fmtCurrency(listing.adr) +
    (listing.occupancy != null ? " · Occ: " + fmtPct(listing.occupancy) : "")
  );
}

function drawMarkers() {
  if (!MARKER_LAYER) return;
  MARKER_LAYER.clearLayers();
  ALL_LISTINGS.forEach((listing) => {
    if (!ACTIVE_TIERS.has(listing.tier)) return;

    const color = MAP_CONFIG.tierColors[listing.tier];
    const marker = L.circleMarker([listing.lat, listing.lng], {
      radius: 4,
      color: color,
      weight: 1,
      fillColor: color,
      fillOpacity: 0.65,
    });
    marker.bindTooltip(markerTooltipHtml(listing), { sticky: true });
    MARKER_LAYER.addLayer(marker);
  });
}

function drawZipOverlay(payload) {
  if (!ZIP_LAYER) return;
  ZIP_LAYER.clearLayers();
  fetch("data/zip-boundaries.geojson")
    .then((r) => (r.ok ? r.json() : Promise.reject()))
    .then((geojson) => {
      L.geoJSON(geojson, {
        style: { color: "#485a55", weight: 1, opacity: 0.45, dashArray: "4 3", fillOpacity: 0.02 },
      }).addTo(ZIP_LAYER);
    })
    .catch(() => {
      (payload.zipApprox || []).forEach((z) => {
        const circle = L.circle([z.lat, z.lng], {
          radius: z.radiusDeg * 111000,
          color: "#485a55",
          weight: 1,
          opacity: 0.35,
          dashArray: "4 4",
          fillOpacity: 0.02,
          interactive: false,
        });
        circle.bindTooltip("ZIP " + z.zip + " (" + z.n + " listings, approximate area)", { sticky: true });
        ZIP_LAYER.addLayer(circle);
        ZIP_LAYER.addLayer(
          L.marker([z.lat, z.lng], {
            icon: L.divIcon({ className: "zip-label", html: z.zip, iconSize: [40, 14] }),
            interactive: false,
          })
        );
      });
    });
}

function renderMapLegend(payload) {
  const host = document.getElementById("map-legend");
  if (!host) return;
  let html = "<h4>Revenue tier</h4>";
  Object.keys(MAP_CONFIG.tierLabels).forEach((tier) => {
    html +=
      '<div class="legend-row"><span class="legend-swatch" style="background:' +
      MAP_CONFIG.tierColors[tier] +
      '"></span>' +
      MAP_CONFIG.tierLabels[tier] +
      "</div>";
  });
  html +=
    '<p class="legend-note">n=' +
    payload.n +
    " listings. " +
    payload.tierNote +
    " ZIP outlines are approximate (centroid + radius from listing coordinates), not authoritative ZCTA boundaries; see map.js for the real-boundary integration point.</p>";
  host.innerHTML = html;
}

function renderMapFilters() {
  const host = document.getElementById("map-filters");
  if (!host) return;
  let html = '<h4>Filter by revenue tier</h4><div class="filter-group" data-filter-group="tier">';
  Object.keys(MAP_CONFIG.tierLabels).forEach((tier) => {
    html +=
      '<label class="filter-row"><input type="checkbox" checked data-tier="' +
      tier +
      '"> ' +
      MAP_CONFIG.tierLabels[tier] +
      "</label>";
  });
  html += '</div><h4>ZIP overlay</h4><div class="filter-group"><label class="filter-row"><input type="checkbox" id="zip-overlay-toggle"> Show ZIP areas (approximate)</label></div>';
  host.innerHTML = html;

  host.querySelectorAll("input[data-tier]").forEach((input) => {
    input.addEventListener("change", () => {
      const tier = input.dataset.tier;
      if (input.checked) ACTIVE_TIERS.add(tier);
      else ACTIVE_TIERS.delete(tier);
      drawMarkers();
    });
  });
  const zipToggle = host.querySelector("#zip-overlay-toggle");
  if (zipToggle) {
    zipToggle.addEventListener("change", () => {
      if (!ZIP_LAYER) return;
      if (zipToggle.checked) LEAFLET_MAP.addLayer(ZIP_LAYER);
      else LEAFLET_MAP.removeLayer(ZIP_LAYER);
    });
  }
}

function mapInterpretationHtml(payload) {
  return (
    "<p>Every dot is one listing in the cleaned market dataset, colored by market-wide revenue tier. " +
    (MAP_CONFIG.marketInterpretation || "") +
    "</p>"
  );
}

function initMap() {
  const container = document.getElementById("leaflet-map");
  if (!container) return;
  LEAFLET_MAP = L.map(container).setView(MAP_CONFIG.center, MAP_CONFIG.zoom);
  L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
    attribution: "&copy; OpenStreetMap contributors",
    maxZoom: 17,
  }).addTo(LEAFLET_MAP);
  MARKER_LAYER = L.layerGroup().addTo(LEAFLET_MAP);
  ZIP_LAYER = L.layerGroup();

  loadListingsPayload()
    .then((payload) => {
      ALL_LISTINGS = payload.listings || [];
      renderMapLegend(payload);
      renderMapFilters();
      drawMarkers();
      drawZipOverlay(payload);
      const interp = document.getElementById("map-interpretation");
      if (interp) interp.innerHTML = mapInterpretationHtml(payload);
    })
    .catch(() => {
      const interp = document.getElementById("map-interpretation");
      if (interp)
        interp.innerHTML =
          '<p class="map-error">Could not load data/listings.json. Run <code>python3 scripts/generate_webpage_map_data.py</code> from the repo root, then reload.</p>';
    });
}

function cleanupFourBrCompMap() {
  if (FOUR_BR_COMP_MAP) {
    FOUR_BR_COMP_MAP.remove();
    FOUR_BR_COMP_MAP = null;
    FOUR_BR_COMP_MARKER_LAYER = null;
  }
  FOUR_BR_ACTIVE_CATEGORIES = new Set(Object.keys(MAP_CONFIG.fourBrCompCategories));
}

function fourBrCategoryFor(comp) {
  return comp.category || comp.tier || "target";
}

function fourBrMapComps(box, listings) {
  const byId = {};
  (listings || []).forEach((listing) => {
    byId[listing.id] = listing;
  });

  const comps = [];
  ((box.revenueTiers && box.revenueTiers.comps) || []).forEach((comp) => {
    comps.push(Object.assign({ category: comp.tier || "target" }, comp));
  });
  ((box.revenueTiers && box.revenueTiers.ceilingComps) || []).forEach((comp) => {
    comps.push(Object.assign({ category: "ceiling" }, comp));
  });
  (box.counterexamples || []).forEach((comp) => {
    comps.push(Object.assign({ category: "counterexample" }, comp));
  });

  return comps
    .map((comp) => Object.assign({}, comp, { listing: byId[comp.propertyId] }))
    .filter((comp) => comp.listing && comp.listing.lat != null && comp.listing.lng != null);
}

function fourBrPopupHtml(comp) {
  const category = MAP_CONFIG.fourBrCompCategories[fourBrCategoryFor(comp)];
  let html =
    "<strong>" + escapeHtml(comp.name) + "</strong><br>" +
    escapeHtml(category ? category.label : fourBrCategoryFor(comp)) + "<br>" +
    escapeHtml(comp.city) + ", " + MAP_CONFIG.stateAbbr + " " + escapeHtml(comp.zip) +
    (comp.sleeps ? " · Sleeps " + escapeHtml(comp.sleeps) : "") +
    (comp.baths ? " · " + escapeHtml(comp.baths) + " baths" : "") +
    "<br>Revenue: " + fmtCurrency(comp.revenue) +
    " · ADR: " + fmtCurrency(comp.adr) +
    (comp.occupancy != null ? " · Occ: " + fmtPct(comp.occupancy) : "");
  if (comp.why || comp.explanation) {
    html += '<br><span class="map-popup-note">' + escapeHtml(comp.why || comp.explanation) + "</span>";
  }
  html += '<br><a href="' + escapeHtml(comp.url) + '" target="_blank" rel="noopener">View on Airbnb</a>';
  return html;
}

function drawFourBrCompMarkers(comps) {
  if (!FOUR_BR_COMP_MARKER_LAYER) return;
  FOUR_BR_COMP_MARKER_LAYER.clearLayers();
  const bounds = [];
  comps.forEach((comp) => {
    const categoryKey = fourBrCategoryFor(comp);
    if (!FOUR_BR_ACTIVE_CATEGORIES.has(categoryKey)) return;

    const category = MAP_CONFIG.fourBrCompCategories[categoryKey] || MAP_CONFIG.fourBrCompCategories.target;
    const latLng = [comp.listing.lat, comp.listing.lng];
    const marker = L.circleMarker(latLng, {
      radius: category.radius || 8,
      color: category.stroke || "#0b4b40",
      weight: 2,
      fillColor: category.color,
      fillOpacity: 0.92,
    });
    marker.bindPopup(fourBrPopupHtml(comp), { maxWidth: 320 });
    marker.bindTooltip(escapeHtml(comp.name), { sticky: true });
    FOUR_BR_COMP_MARKER_LAYER.addLayer(marker);
    bounds.push(latLng);
  });
  if (bounds.length) {
    FOUR_BR_COMP_MAP.fitBounds(bounds, { padding: [28, 28], maxZoom: 11 });
  }
}

function renderFourBrCompMapLegend(host, comps) {
  if (!host) return;
  let html = "<h4>4BR comp map</h4>";
  Object.keys(MAP_CONFIG.fourBrCompCategories).forEach((key) => {
    const c = MAP_CONFIG.fourBrCompCategories[key];
    const count = comps.filter((comp) => fourBrCategoryFor(comp) === key).length;
    html +=
      '<div class="legend-row"><span class="legend-swatch legend-swatch--outlined" style="background:' +
      c.color +
      '"></span>' +
      c.label +
      ' <span class="legend-count">(' + count + ")</span></div>";
  });
  html += '<p class="legend-note">Markers are the named 4BR underwriting comps, ceiling/reference comps, and counterexamples from the 4BR deep dive. Coordinates are joined by Property ID from the cleaned market dataset.</p>';
  host.innerHTML = html;
}

function renderFourBrCompMapFilters(host, comps) {
  if (!host) return;
  let html = '<h4>Filter comp markers</h4><div class="filter-group" data-filter-group="4br-comps">';
  Object.keys(MAP_CONFIG.fourBrCompCategories).forEach((key) => {
    const c = MAP_CONFIG.fourBrCompCategories[key];
    const count = comps.filter((comp) => fourBrCategoryFor(comp) === key).length;
    html +=
      '<label class="filter-row"><input type="checkbox" checked data-fourbr-category="' +
      key +
      '"> ' +
      c.label +
      " (" + count + ")</label>";
  });
  html += "</div>";
  host.innerHTML = html;
  host.querySelectorAll("input[data-fourbr-category]").forEach((input) => {
    input.addEventListener("change", () => {
      const key = input.dataset.fourbrCategory;
      if (input.checked) FOUR_BR_ACTIVE_CATEGORIES.add(key);
      else FOUR_BR_ACTIVE_CATEGORIES.delete(key);
      drawFourBrCompMarkers(comps);
    });
  });
}

function initFourBrCompMap(box) {
  const container = document.getElementById("fourbr-comp-map");
  if (!container || !box) return;
  cleanupFourBrCompMap();
  FOUR_BR_COMP_MAP = L.map(container).setView(MAP_CONFIG.center, MAP_CONFIG.zoom);
  L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
    attribution: "&copy; OpenStreetMap contributors",
    maxZoom: 17,
  }).addTo(FOUR_BR_COMP_MAP);
  FOUR_BR_COMP_MARKER_LAYER = L.layerGroup().addTo(FOUR_BR_COMP_MAP);

  loadListingsPayload()
    .then((payload) => {
      const comps = fourBrMapComps(box, payload.listings || []);
      renderFourBrCompMapLegend(document.getElementById("fourbr-comp-map-legend"), comps);
      renderFourBrCompMapFilters(document.getElementById("fourbr-comp-map-filters"), comps);
      drawFourBrCompMarkers(comps);
      window.setTimeout(() => {
        if (FOUR_BR_COMP_MAP) FOUR_BR_COMP_MAP.invalidateSize();
      }, 0);
    })
    .catch(() => {
      const note = document.getElementById("fourbr-comp-map-note");
      if (note) note.innerHTML = '<p class="map-error">Could not load the 4BR comp map data.</p>';
    });
}

// ---------------------------------------------------------------------------
// 1-2BR interactive comp map (Section 5 deep dive) — population restricted
// to bedrooms 1-2 only. Revenue tiers are computed client-side from that
// filtered population's own distribution (segment-relative percentiles, NOT
// the market-wide tiers used by the Section 3 map), then the 9 named
// "chosen revenue comp set" listings (box.locationGuidance.revenueComps,
// joined by Property ID) are drawn as distinct outlined markers on top,
// mirroring the 4BR comp map's pattern above.
// ---------------------------------------------------------------------------
let ONE_TWO_BR_MAP = null;
let ONE_TWO_BR_MARKER_LAYER = null;
let ONE_TWO_BR_ACTIVE_TIERS = new Set(["top10", "top25", "bottom75"]);

function cleanupOneTwoBrCompMap() {
  if (ONE_TWO_BR_MAP) {
    ONE_TWO_BR_MAP.remove();
    ONE_TWO_BR_MAP = null;
    ONE_TWO_BR_MARKER_LAYER = null;
  }
  ONE_TWO_BR_ACTIVE_TIERS = new Set(["top10", "top25", "bottom75"]);
}

function percentile(sortedVals, p) {
  if (!sortedVals.length) return null;
  const k = (sortedVals.length - 1) * p;
  const f = Math.floor(k);
  const c = Math.min(f + 1, sortedVals.length - 1);
  if (f === c) return sortedVals[f];
  return sortedVals[f] + (sortedVals[c] - sortedVals[f]) * (k - f);
}

function oneTwoBrListings(listings) {
  return (listings || []).filter((l) => l.bedrooms === 1 || l.bedrooms === 2);
}

function oneTwoBrTierThresholds(segmentListings) {
  const revenues = segmentListings
    .map((l) => l.revenue)
    .filter((r) => r != null)
    .sort((a, b) => a - b);
  return { p75: percentile(revenues, 0.75), p90: percentile(revenues, 0.90), n: revenues.length };
}

function oneTwoBrTierFor(listing, thresholds) {
  if (listing.revenue == null) return "bottom75";
  if (listing.revenue >= thresholds.p90) return "top10";
  if (listing.revenue >= thresholds.p75) return "top25";
  return "bottom75";
}

function oneTwoBrCompsFor(box, listingsById) {
  const revenueComps = (box.locationGuidance && box.locationGuidance.revenueComps) || [];
  return revenueComps
    .map((comp) => Object.assign({}, comp, { listing: listingsById[comp.propertyId] }))
    .filter((comp) => comp.listing && comp.listing.lat != null && comp.listing.lng != null);
}

function drawOneTwoBrMarkers(segmentListings, thresholds, comps) {
  if (!ONE_TWO_BR_MARKER_LAYER) return;
  ONE_TWO_BR_MARKER_LAYER.clearLayers();
  const compIds = new Set(comps.map((c) => c.propertyId));

  segmentListings.forEach((listing) => {
    const tier = oneTwoBrTierFor(listing, thresholds);
    if (!ONE_TWO_BR_ACTIVE_TIERS.has(tier)) return;
    if (compIds.has(listing.id)) return; // drawn separately, outlined, below
    const color = ONE_TWO_BR_MAP_CONFIG.tierColors[tier];
    const marker = L.circleMarker([listing.lat, listing.lng], {
      radius: 4,
      color: color,
      weight: 1,
      fillColor: color,
      fillOpacity: 0.65,
    });
    marker.bindTooltip(markerTooltipHtml(listing), { sticky: true });
    ONE_TWO_BR_MARKER_LAYER.addLayer(marker);
  });

  const style = ONE_TWO_BR_MAP_CONFIG.compStyle;
  comps.forEach((comp) => {
    const tier = oneTwoBrTierFor(comp.listing, thresholds);
    if (!ONE_TWO_BR_ACTIVE_TIERS.has(tier)) return;
    const marker = L.circleMarker([comp.listing.lat, comp.listing.lng], {
      radius: style.radius,
      color: style.stroke,
      weight: 2,
      fillColor: style.color,
      fillOpacity: 0.95,
    });
    marker.bindPopup(
      "<strong>" + escapeHtml(comp.name) + "</strong><br>" + markerTooltipHtml(comp.listing).replace("<strong>" + escapeHtml(comp.listing.title) + "</strong><br>", ""),
      { maxWidth: 300 }
    );
    marker.bindTooltip(escapeHtml(comp.name), { sticky: true });
    ONE_TWO_BR_MARKER_LAYER.addLayer(marker);
  });
}

function renderOneTwoBrMapLegend(host, thresholds, comps) {
  if (!host) return;
  let html = "<h4>1-2BR revenue tier</h4>";
  ["top10", "top25", "bottom75"].forEach((tier) => {
    html +=
      '<div class="legend-row"><span class="legend-swatch" style="background:' +
      ONE_TWO_BR_MAP_CONFIG.tierColors[tier] +
      '"></span>' +
      ONE_TWO_BR_MAP_CONFIG.tierLabelPrefix[tier] +
      "</div>";
  });
  html +=
    '<div class="legend-row"><span class="legend-swatch legend-swatch--outlined" style="background:' +
    ONE_TWO_BR_MAP_CONFIG.compStyle.color +
    '"></span>' +
    ONE_TWO_BR_MAP_CONFIG.compStyle.label +
    " (" + comps.length + ")</div>";
  html +=
    '<p class="legend-note">n=' +
    thresholds.n +
    " 1-2BR listings. Tiers computed from this 1-2BR-only population (P75=$" +
    Math.round(thresholds.p75).toLocaleString() +
    ", P90=$" +
    Math.round(thresholds.p90).toLocaleString() +
    "), not the market-wide tiers used in Section 3.</p>";
  host.innerHTML = html;
}

function renderOneTwoBrMapFilters(host, segmentListings, thresholds, comps) {
  if (!host) return;
  let html = '<h4>Filter by revenue tier</h4><div class="filter-group" data-filter-group="onetwobr-tier">';
  ["top10", "top25", "bottom75"].forEach((tier) => {
    html +=
      '<label class="filter-row"><input type="checkbox" checked data-onetwobr-tier="' +
      tier +
      '"> ' +
      ONE_TWO_BR_MAP_CONFIG.tierLabelPrefix[tier] +
      "</label>";
  });
  html += "</div>";
  host.innerHTML = html;
  host.querySelectorAll("input[data-onetwobr-tier]").forEach((input) => {
    input.addEventListener("change", () => {
      const tier = input.dataset.onetwobrTier;
      if (input.checked) ONE_TWO_BR_ACTIVE_TIERS.add(tier);
      else ONE_TWO_BR_ACTIVE_TIERS.delete(tier);
      drawOneTwoBrMarkers(segmentListings, thresholds, comps);
    });
  });
}

function initOneTwoBrCompMap(box) {
  const container = document.getElementById("onetwobr-comp-map");
  if (!container || !box) return;
  cleanupOneTwoBrCompMap();
  ONE_TWO_BR_MAP = L.map(container).setView(MAP_CONFIG.center, MAP_CONFIG.zoom);
  L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
    attribution: "&copy; OpenStreetMap contributors",
    maxZoom: 17,
  }).addTo(ONE_TWO_BR_MAP);
  ONE_TWO_BR_MARKER_LAYER = L.layerGroup().addTo(ONE_TWO_BR_MAP);

  loadListingsPayload()
    .then((payload) => {
      const listingsById = {};
      (payload.listings || []).forEach((l) => (listingsById[l.id] = l));
      const segmentListings = oneTwoBrListings(payload.listings);
      const thresholds = oneTwoBrTierThresholds(segmentListings);
      const comps = oneTwoBrCompsFor(box, listingsById);
      renderOneTwoBrMapLegend(document.getElementById("onetwobr-comp-map-legend"), thresholds, comps);
      renderOneTwoBrMapFilters(document.getElementById("onetwobr-comp-map-filters"), segmentListings, thresholds, comps);
      drawOneTwoBrMarkers(segmentListings, thresholds, comps);
      window.setTimeout(() => {
        if (ONE_TWO_BR_MAP) ONE_TWO_BR_MAP.invalidateSize();
      }, 0);
    })
    .catch(() => {
      const note = document.getElementById("onetwobr-comp-map-note");
      if (note) note.innerHTML = '<p class="map-error">Could not load the 1-2BR comp map data.</p>';
    });
}
